[phases.setup]
nixPkgs = ["python312", "nodejs_20"]

[phases.install]
cmds = [
  "python -m venv --copies /opt/venv",
  "/opt/venv/bin/pip install -r requirements.txt"
]

[phases.build]
cmds = [
  "cd frontend && npm install && npm run build && cd ..",
  "/opt/venv/bin/python manage.py collectstatic --noinput --clear",
  "cp -r frontend/dist/* staticfiles/"
]

[start]
cmd = "/opt/venv/bin/python manage.py migrate && /opt/venv/bin/gunicorn volunteer_tracker.wsgi:application --bind 0.0.0.0:$PORT"