[phases.setup]
nixPkgs = ["python312", "nodejs_20"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.build]
cmds = [
    "cd frontend && npm install && npm run build && cd ..",
    "python manage.py collectstatic --noinput --clear",
    "cp -r frontend/dist/* staticfiles/"
]

[start]
cmd = "python manage.py migrate && gunicorn volunteer_tracker.wsgi:application --bind 0.0.0.0:$PORT"
