[phases.setup]
nixPkgs = ["python312", "nodejs_20"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.build]
cmds = [
    "echo '=== Building Frontend ==='",
    "cd frontend && npm install && npm run build",
    "echo '=== Frontend build complete ==='",
    "ls -la dist/",
    "cd ..",
    "echo '=== Creating staticfiles directory ==='",
    "mkdir -p staticfiles",
    "echo '=== Copying frontend build to staticfiles ==='",
    "cp -rv frontend/dist/* staticfiles/",
    "ls -la staticfiles/",
    "echo '=== Running collectstatic ==='",
    "python manage.py collectstatic --noinput --clear",
    "echo '=== Final staticfiles contents ==='",
    "ls -la staticfiles/"
]

[start]
cmd = "python manage.py migrate && gunicorn volunteer_tracker.wsgi:application --bind 0.0.0.0:$PORT"
