providers = ["python", "node"]

[phases.setup]
nixPkgs = ["python312", "nodejs_20", "postgresql"]

[phases.build]
cmds = [
  "cd frontend && npm ci && npm run build && cd ..",
  "python -m pip install -r requirements.txt",
  "python manage.py collectstatic --noinput"
]

[phases.deploy]
cmds = ["python manage.py migrate && gunicorn volunteer_tracker.wsgi:application --bind 0.0.0.0:$PORT"]

[start]
cmd = "gunicorn volunteer_tracker.wsgi:application --bind 0.0.0.0:$PORT"