[phases.setup]
nixPkgs = ["python312"]

[phases.install]
cmds = [
  "rm -rf /opt/venv || true",
  "python -m venv --copies /opt/venv",
  "/opt/venv/bin/pip install --upgrade pip",
  "/opt/venv/bin/pip install --no-cache-dir --force-reinstall anthropic==0.15.0 openai==1.52.0",
  "/opt/venv/bin/pip install --no-cache-dir -r requirements.txt"
]

[start]
cmd = "/opt/venv/bin/python manage.py migrate && /opt/venv/bin/gunicorn volunteer_tracker.wsgi:application --bind 0.0.0.0:$PORT"