[phases.setup]
nixPkgs = ["python312", "nodejs_20"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.build]
cmds = [
    "echo '=== Building frontend ==='",
    "cd frontend && npm install && npm run build && cd ..",
    "echo '=== Frontend dist contents ==='",
    "ls -la frontend/dist/ || echo 'dist directory not found'",
    "echo '=== Running collectstatic ==='",
    "python manage.py collectstatic --noinput --clear",
    "echo '=== Copying frontend to staticfiles ==='",
    "cp -rv frontend/dist/* staticfiles/ || echo 'Copy failed'",
    "echo '=== Final staticfiles contents ==='",
    "ls -la staticfiles/ || echo 'staticfiles directory not found'"
]

[start]
cmd = "python manage.py migrate && gunicorn volunteer_tracker.wsgi:application --bind 0.0.0.0:$PORT"
