[phases.setup]
nixPkgs = ["...", "nodejs_18"]
aptPkgs = ["..."]

[phases.install]
cmds = [
    "python -m venv /opt/venv",
    ". /opt/venv/bin/activate && pip install -r requirements.txt"
]

[phases.build]
cmds = [
    "cd frontend && npm ci && npm run build && cd ..",
    ". /opt/venv/bin/activate && python manage.py collectstatic --noinput"
]

[start]
cmd = ". /opt/venv/bin/activate && python manage.py migrate && gunicorn volunteer_tracker.wsgi:application --bind 0.0.0.0:$PORT"
