[phases.setup]
nixPkgs = ["python312", "nodejs_20"]

[phases.install]
cmds = ["pip install -r requirements.txt"]

[phases.build]
cmds = [
    "cd frontend && npm install && npm run build && cd ..",
    "mkdir -p staticfiles",
    "cp -r frontend/dist/* staticfiles/ || true",
    "python manage.py collectstatic --noinput --clear"
]

[start]
cmd = "python manage.py migrate && gunicorn volunteer_tracker.wsgi:application --bind 0.0.0.0:$PORT"
