[phases.setup]
nixPkgs = ["python312"]

[phases.install]
cmds = [
  "python -m venv --copies /opt/venv",
  "/opt/venv/bin/pip install -r requirements.txt"
]

[start]
cmd = "/opt/venv/bin/python manage.py migrate && /opt/venv/bin/gunicorn volunteer_tracker.wsgi:application --bind 0.0.0.0:$PORT"