# Generated by Django 5.0.1 on 2025-10-03 21:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('volunteers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Interaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('interaction_date', models.DateField()),
                ('discussion_notes', models.TextField()),
                ('topics', models.JSONField(blank=True, default=list)),
                ('needs_followup', models.BooleanField(default=False)),
                ('followup_date', models.DateField(blank=True, null=True)),
                ('followup_notes', models.TextField(blank=True, null=True)),
                ('followup_completed', models.BooleanField(default=False)),
                ('followup_completed_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('team_member', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interactions', to=settings.AUTH_USER_MODEL)),
                ('volunteer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interactions', to='volunteers.volunteer')),
            ],
            options={
                'db_table': 'interactions',
                'ordering': ['-interaction_date'],
                'indexes': [models.Index(fields=['volunteer'], name='interaction_volunte_9937f0_idx'), models.Index(fields=['team_member'], name='interaction_team_me_72a7b9_idx'), models.Index(fields=['interaction_date'], name='interaction_interac_f32f52_idx'), models.Index(fields=['needs_followup', 'followup_completed'], name='interaction_needs_f_eae512_idx')],
            },
        ),
    ]
