# Generated by Django 5.0.1 on 2025-10-04 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='teams',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
