# Generated by Django 5.0.1 on 2025-10-10 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('volunteers', '0002_volunteer_teams'),
    ]

    operations = [
        migrations.AddField(
            model_name='volunteer',
            name='is_archived',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='volunteer',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('archived', 'Archived')], default='active', max_length=20),
        ),
        migrations.AddIndex(
            model_name='volunteer',
            index=models.Index(fields=['is_archived'], name='volunteers_is_arch_5d17c6_idx'),
        ),
    ]
